### ISSUE TITLE
Does not suppport '+' in #define and function calls in [Files] and [Run]

### ISSUE THREAD

**Issue by davew945** [KleinerHacker/intellij-plugin.inno-setup#1]
Hi:
Thank you for the plugin. I see that you have a lot of time invested in it.

1. The parser fails on '+' in the #define section. This stops the rest of the page from being color-coded, etc. It also leads to the error 'Cannot find required section Setup'. Parser error is

#define FLINTSTONES  "Fred " + "Wilma"
**< preprocessor value > or IssTokenType.EOL expected, got '+'**

2. The parser also fails on the '(' in function calls added to [Files] and [Run], etc. Parser error is

[Files]
Source:...; DestDir:...; AfterInstall: FileReplaceString(file,search,replace)
**';', IssTokenType.EOL or IssTokenType.NAME expected, got '('**

3. This biggest issue is that once the parser fails, none of the rest of the page is parsed properly.
   It would be a huge improvement if it just ignored lines with specific 'errors'

The plugin works fine when I don't use these features, but I need them, esp. #2 and #3.
I looked in your source and it is too complicated for me to easily figure out. 
Even hints on how to fix the source would be useful.

Thank you.

**Comment by KleinerHacker** [comment]
I fix the problem in 0.3.1

**Comment by KleinerHacker** [comment]
@davew945 fixed in 0.3.1, updated to jetbrains plugin repository now, see [https://plugins.jetbrains.com/plugin/10288-inno-setup-support](url) or new release here.
